// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * THIS IS AN EXAMPLE CONTRACT THAT USES HARDCODED VALUES FOR CLARITY.
 * THIS IS AN EXAMPLE CONTRACT THAT USES UN-AUDITED CODE.
 * DO NOT USE THIS CODE IN PRODUCTION.
 * 
 * 此合约包含带重试功能的 JavaScript 代码
 * API 请求失败时会自动重试最多 3 次
 */
abstract contract FunctionsSourceRetry {
    string public getNftMetadata =
        "const { ethers } = await import('npm:ethers@6.10.0');"
        "const Hash = await import('npm:ipfs-only-hash@4.0.0');"
        "const MAX_RETRIES = 3;"
        "const API_URL = 'https://api.bridgedataoutput.com/api/v2/OData/test/Property(\\'P_69179ef9b7bb783d6039ab66\\')?access_token=6baca547742c6f96a6ff71b138424f21';"
        "let lastError = null;"
        "for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {"
        "  try {"
        "    if (attempt > 0) {"
        "      console.log(`Retry attempt ${attempt} of ${MAX_RETRIES}`);"
        "      await new Promise(resolve => setTimeout(resolve, 1000 * attempt));"
        "    }"
        "    const apiResponse = await Functions.makeHttpRequest({"
        "      url: API_URL,"
        "      timeout: 5000,"
        "      method: 'GET',"
        "    });"
        "    if (apiResponse.error) {"
        "      throw new Error(`API error: ${apiResponse.error}`);"
        "    }"
        "    if (!apiResponse || !apiResponse.data) {"
        "      throw new Error('API response is invalid or empty');"
        "    }"
        "    const data = apiResponse.data;"
        "    const realEstateAddress = data.UnparsedAddress || '';"
        "    const yearBuilt = Number(data.YearBuilt) || 0;"
        "    const lotSizeSquareFeet = Number(data.LotSizeSquareFeet) || 0;"
        "    const livingArea = Number(data.LivingArea) || 0;"
        "    const bedroomsTotal = Number(data.BedroomsTotal) || 0;"
        "    const metadata = {"
        "      name: 'Real Estate Token',"
        "      attributes: ["
        "        { trait_type: 'realEstateAddress', value: realEstateAddress },"
        "        { trait_type: 'yearBuilt', value: yearBuilt },"
        "        { trait_type: 'lotSizeSquareFeet', value: lotSizeSquareFeet },"
        "        { trait_type: 'livingArea', value: livingArea },"
        "        { trait_type: 'bedroomsTotal', value: bedroomsTotal }"
        "      ]"
        "    };"
        "    const metadataString = JSON.stringify(metadata);"
        "    const ipfsCid = await Hash.of(metadataString);"
        "    return Functions.encodeString(`ipfs://${ipfsCid}`);"
        "  } catch (error) {"
        "    lastError = error;"
        "    console.error(`Attempt ${attempt + 1} failed:`, error.message);"
        "    if (attempt === MAX_RETRIES) {"
        "      throw new Error(`API request failed after ${MAX_RETRIES + 1} attempts. Last error: ${error.message}`);"
        "    }"
        "  }"
        "}";

    string public getPrices =
        "const { ethers } = await import('npm:ethers@6.10.0');"
        "const abiCoder = ethers.AbiCoder.defaultAbiCoder();"
        "const tokenId = args[0];"
        "const MAX_RETRIES = 3;"
        "const API_URL = 'https://api.bridgedataoutput.com/api/v2/OData/test/Property(\\'P_69179ef9b7bb783d6039ab66\\')?access_token=6baca547742c6f96a6ff71b138424f21';"
        "let lastError = null;"
        "for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {"
        "  try {"
        "    if (attempt > 0) {"
        "      console.log(`Retry attempt ${attempt} of ${MAX_RETRIES}`);"
        "      await new Promise(resolve => setTimeout(resolve, 1000 * attempt));"
        "    }"
        "    const apiResponse = await Functions.makeHttpRequest({"
        "      url: API_URL,"
        "      timeout: 5000,"
        "      method: 'GET',"
        "    });"
        "    if (apiResponse.error) {"
        "      throw new Error(`API error: ${apiResponse.error}`);"
        "    }"
        "    if (!apiResponse || !apiResponse.data) {"
        "      throw new Error('API response is invalid or empty');"
        "    }"
        "    const data = apiResponse.data;"
        "    const listPrice = Number(data.ListPrice) || 0;"
        "    const originalListPrice = Number(data.OriginalListPrice) || 0;"
        "    const taxAssessedValue = Number(data.TaxAssessedValue) || 0;"
        "    const encoded = abiCoder.encode(['uint256', 'uint256', 'uint256', 'uint256'], [tokenId, listPrice, originalListPrice, taxAssessedValue]);"
        "    return ethers.getBytes(encoded);"
        "  } catch (error) {"
        "    lastError = error;"
        "    console.error(`Attempt ${attempt + 1} failed:`, error.message);"
        "    if (attempt === MAX_RETRIES) {"
        "      throw new Error(`API request failed after ${MAX_RETRIES + 1} attempts. Last error: ${error.message}`);"
        "    }"
        "  }"
        "}";
}
